apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-scaler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-scaler
  template:
    metadata:
      labels:
        app: auto-scaler
    spec:
      containers:
      - name: scaler
        image: myrepo/autoscaler:latest
        ports:
        - containerPort: 5000
